name: Clean the registry

on: delete

jobs:
  branch-cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Print a message
      shell: bash
      run: echo "Deleted the branch ${{ github.event.ref }}"
