name: clean the registry

on: delete

jobs:
  delete-branch-cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Setup gsutil
      run: |
        echo "Setup the client"
        echo "Deleted the branch ${{ github.event.ref }}"

    - name: Clean the registry
      shell: bash
      run: |
        echo "Deleting the branch ${{ github.event.ref }}"
        # gcloud container images list-tags \
        #   --format='get(digest)' \
        #   --filter="tags:${{ github.event.ref }}" \
        #   ${{ secrets.IMAGE_URI }} | xargs -I{} \
        #   gcloud container images delete \
        #   -q --force-delete-tags ${{ secrets.IMAGE_URI }}@{}

    - name: Release credentials
      if: always()
      run: |
        echo "Tear down the credientials for the client"
