name: submit in container
on:
  issue_comment:
    types: [created]

jobs:
  submit:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:

    - name: Parse message
      id: parse-script
      run: |
        BUILD_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        echo "${BUILD_ID}"
        echo "::set-output name=modified_message::$(sed "s|/build|[/build](${BUILD_URL})|" <<< "${{ github.event.comment.body }}")"

    - name: "Get the source code"
      uses: actions/checkout@v2

    - name: Execute the training script
      id: submit-script
      run: |
        result_code=${PIPESTATUS[0]}
        echo "::set-output name=my_payload::$(ls -l | grep req)"
        exit ${result_code}

    - name: Update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        body: ${{ steps.parse-script.outputs.modified_message }}
        reactions: rocket
        edit-mode: replace

    - name: Fire the coment
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'You have triggered the build! 🚀 \n' +
                  '```bash\n${{ steps.submit-script.outputs.my_payload }}\n```\n'
          })
