name: submit in container
on:
  issue_comment:
    types: [created]

jobs:
  submit:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:

    - name: Parse message
      id: parse-script
      run: |
        BUILD_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        echo "${BUILD_ID}"
        echo "::set-output name=modified_message::$(sed "s|/build|[/build](${BUILD_URL})|" <<< "${{ github.event.comment.body }}")"

    - name: "Get the source code"
      uses: actions/checkout@v2

    - name: Execute the training script
      id: submit-script
      run: |
        curl www.google.com > /dev/null
    - name: Update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        body: ${{ steps.parse-script.outputs.modified_message }}
        reactions: rocket
        edit-mode: replace
