name: manual submit on comment
on:
  issue_comment:
    types: [created]

jobs:
  bump-dataset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute for pull request comments only
      if: github.event.issue.pull_request
      run: |
        echo "This is a pull request comment: ${{ github.event.comment.body }}"

    - name: Example variable usage
      run: echo "The latest dataset is ${{ github.event.inputs.dataset }}"

    - name: Submit the main script
      id: submit-script
      run: |
        ls -ltr 2>&1 | tee test.log
        result_code=${PIPESTATUS[0]}
        echo "::set-output name=FOLDER_CONTENT::$(cat test.log | grep runner)"
        exit ${result_code}

    - name: Get the message 
      run: echo "The content of the folder is ${{ steps.submit-script.outputs.FOLDER_CONTENT }}"
