name: submit training pipeline
on:
  issue_comment:
    types: [created]

jobs:
  submit:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/start')
    runs-on: ubuntu-latest
    container: gcr.io/cloud-builders/gsutil

    steps:

    - name: Parse message
      id: parse-script
      shell: bash
      run: |
        BUILD_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        echo "${BUILD_ID}"
        echo "::set-output name=modified_message::$(sed "s|/start|[/start](${BUILD_URL})|" <<< "${{ github.event.comment.body }}")"

    - name: Parse the
    - name: Update comment with the link to this build
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        body: ${{ steps.parse-script.outputs.modified_message }}
        reactions: rocket
        edit-mode: replace
    
    - name: "Get the source code"
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      id: extract_branch
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo ${{ github.event.pull_request.head.ref }}
        echo ${{ github.base_ref }}

    - name: "Get ref head"
      run: echo "${{ steps.extract_branch.outputs.branch }}"
      
      
    - name: "Check the source code version"
      run: |
         echo "${{ toJSON(github) }}"

    
    - name: Parse message
      id: parse-scripts
      shell: bash
      run: |
        BUILD_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        echo "${BUILD_ID}"
        echo "::set-output name=modified_message::$(sed "s|/start|[/start](${BUILD_URL})|" <<< "${{ github.event.comment.body }}")"
