name: manual submit
on:
  issue_comment:
    types: [created]

jobs:
  bump-dataset:
    runs-on: ubuntu-latest
    steps:
    - name: Execute for pull request comments only
      if: github.event.issue.pull_request
      run: |
        echo "This is a pull request comment: ${{ github.event.comment.body }}"
