name: Submit Training
on: 
  workflow_dispatch:
    inputs:
      dataset:
        description: Path to Dataset
        default: gs://some-bucket/some-folder
        required: true
jobs:
  show-dataset:
    name: Show the dataset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Example variable usage
      run: |
        echo "${{ github.event.inputs.dataset }}
        ls -ltr
