name: manual submit
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Path to dataset
        default: gs://some-bucket/some-dataset.tar.gz
        required: true
jobs:
  bump-dataset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Example variable usage
      run: echo "The latest version is ${{ github.event.inputs.version }}"
    - name: Submit the main script
      id: submit-script
      run: echo '::set-output name=FOLDER_CONTENT::$(ls -ltra)'
    - name: Get color
      run: echo "The content of the folder is ${{ steps.submit-script.outputs.FOLDER_CONTENT }}"
